### PR TITLE
Chore: Add poetry lock file so releases can be built consistently

### LINKED ISSUE #90: Commit lock file

### PR DESCRIPTION
**Pull request by dark0dave**
closes #90

### CODE REVIEW

**Comment by layday** [comment]
Please remove the upper cap from the Python version. Otherwise LGTM :)

**Comment by dark0dave** [comment]
The upper cap actually prevents issue:

```
$ poetry lock                            
Updating dependencies
Resolving dependencies... (0.1s)

  SolverProblemError

  The current project's Python requirement (>=3.7) is not compatible with some of the required packages Python requirement:
    - questionary requires Python >=3.6,<4.0, so it will not be satisfied for Python >=4.0
  
  Because questionary (1.10.0) requires Python >=3.6,<4.0
   and no versions of questionary match >1.10, questionary is forbidden.
  So, because instawow depends on questionary (>=1.10), version solving failed.

  at ~/.pyenv/versions/3.10.1/lib/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For questionary, a possible solution would be to set the `python` property to ">=3.7,<4.0"

```

**Comment by dark0dave** [comment]
$ poetry --version                
Poetry version 1.1.12
$ python --version
Python 3.10.1
$ pip --version        
pip 21.3.1

**Comment by layday** [comment]
Okay, that's unfortunate. For the record, I don't use Poetry to manage my environment, I only use it to "build" the Python packages I distribute.  If I change instawow's dependencies at some point I might forget to regenerate the lock file.

**Comment by layday** [comment]
I thought I'd open a PR against Questionary to relax the Python version constraint but of course one of Questionary's dependencies pins Python to `< 4` and then Questionary's dependencies can't be locked.  This is the exact situation described in [this blog post](https://iscinumpy.dev/post/poetry-versions/), super frustrating.

**Comment by dark0dave** [comment]
Yes, I too would like to leave python 4 open... That is unfortunate.

**Comment by dark0dave** [comment]
@layday do we want to merge this or?

**Comment by layday** [comment]
I'm not sure, thinking about this some more...

instawow is not (only) distributed as an application.  When you `pip(x) install instawow`, its dependencies are not locked - it pulls the latest versions of everything from PyPI.  So, I won't be using the lock file for testing 'cause it'd be counterproductive.  I won't be using it in development because I only use Poetry as a package builder - I manage my environments with Nix.  I don't like that it constrains the Python version but ultimately it doesn't matter - nobody's using instawow as a library.

If having a lock file is convenient to you I can merge it, but it's gonna lag behind and I make no promises that I'll continue to use Poetry as a package builder :)

**Comment by dark0dave** [comment]
Yeah, not sure either if you are not going to use it then lets not merge it. Its nice to use the latest libraries, but it then becomes a little difficult for me or for someone else to reproduce the build you created (for debugging purposes). For example I need to figure out why the app image (the lovely linux build you made) crashes on my machine and I am not quite sure which versions of certain python libraries you used, makes it difficult for me to retrace your steps. Normally I would go back to the tag, and then use the lock file to pull down the libraries. I am not super familiar with nox/pipx, maybe I am missing a trick?

Thank you for your time and input.

**Comment by layday** [comment]
Yeah, that's a problem not knowing what versions were used when the binaries were built.  On Mac and Linux you can just read the contents of the app bundle but extracting the version numbers is a bit contrived.

Unpacking the app image would help with debugging if you can't read the output/logs:

```
chmod +x instawow-gui.AppImage
./instawow-gui.AppImage --appimage-extract
squashfs-root/AppRun
```

**Comment by dark0dave** [comment]
Thanks! I can see:

image

Lets close this for now. But I would like to have some kind of solution, I am not sure what would work well.

**Comment by layday** [comment]
P.S. I would like to know if the app image is broken. I'm only really able to test the GUI on macOS :(

**Pull request closed without merging**
